name: Delete PR Function
on:
  pull_request:
    types: closed
jobs:
  deploy:
    name: Delete PR function
    # This job runs on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cfg: 
          - { folder: exmaple,  function_path: handler.py }
          - { folder: example2, function_path: handler.py }
    steps:
      - name: Delete PR function
        uses: ./
        env: 
          DELETE_PR_FUNCTION: true
        with:
          cdf_project: datastudio
          cdf_base_url: https://greenfield.cognitedata.com
          cdf_credentials: ${{ secrets.COGNITE_API_KEY }}
          folder: ${{ matrix.cfg.folder }}
          function_path: ${{ matrix.cfg.function_path }}
  